### ISSUE TITLE
Doesn't work with Nuclide

### ISSUE THREAD

**Issue by far-blue** [AtomLinter/linter-phpcs#272]
I recognise Nuclide replaces the normal linter but their API is a good enough replacement for all my other language linters - including linter-php. Only linter-phpcs seems to not work with Nuclide's 'compatible' API. It would be nice if it did work.

**Comment by Arcanemagus** [comment]
They actually consume the same API (that's why it's an API...), and this should be working in there. What issues are you having?

**Comment by far-blue** [comment]
Well, no errors or warnings are reported. If I enable linter then phpcs errors are reported to the linter pane but if I disable linter nothing is reported in nuclide's equivalent 'diagnostics' pane and no markers etc. appear in the editor.

**Comment by Arcanemagus** [comment]
Are you seeing any errors in the console?

If you place a breakpoint [here](https://github.com/AtomLinter/linter-phpcs/blob/v1.6.4/lib/main.js#L168) does it get triggered?

**Comment by Fernando-Marquardt** [comment]
I think I found the problem. It is similar to the problem with the Hack language mentioned in the PRs #268 and #269 

Nuclide is running Diagnostics with the grammar 'text.html.php' instead of 'source.php'. linter-php works, because it is configured to both: https://github.com/AtomLinter/linter-php/blob/master/lib/main.js#L39.

**Comment by Arcanemagus** [comment]
I'd rather Nuclide just stop breaking everything, but that's never going to happen 😛.

Sounds like that's what's needed here @Fernando-Marquardt if you want to submit a PR for it.

**Comment by Fernando-Marquardt** [comment]
@Arcanemagus I took a look at the language-php and it's grammar scope name is configured as 'text.html.php' (https://github.com/atom/language-php/blob/master/grammars/php.cson#L1). source.php is the name given to the internal elements of the grammar.

The linter plugin checks all scopes found in the cursor to find out which linter to execute (https://github.com/steelbrain/linter/blob/master/lib/helpers.js#L28). A simple PHP file returned the following list of scopes: text.html.php, meta.embedded, block.php, source.php, constant.other.php

But the Nuclide Diagnostics, test only the scope name of the grammar in the active editor (https://github.com/facebook/nuclide/blob/master/modules/nuclide-commons-atom/text-event.js#L298).

Which means, we have the grammar scope name 'text.html.php' in both plugins, but the element scope 'source.php' only in the linter plugin. Is it the grammar scope name wrong or is the Nuclide aproach of not testing the cursor scope wrong?

I will submit a PR, no problem. Just wanted to clarify this before doing so.

**Comment by Arcanemagus** [comment]
> the Nuclide Diagnostics, test only the scope name of the grammar in the active editor

> Is it the grammar scope name wrong or is the Nuclide aproach of not testing the cursor scope wrong?

Oh wow, that's a major bug in Nuclide Diagnostics. It definitely needs to be checking the scopes at the cursor in order to handle providers that work with embedded scopes (like ESLint with `eslint-plugin-html` for example which lints JS within HTML).

Linter doesn't use the grammar scope name... I'm not even sure what that _would_ be used for as the TextBuffer isn't marked up with that scope at all.

> by default, every PHP file is open as Hack

Yea, that's another "interesting" choice by the Nuclide developers, I'm sure they did that to make working with their Hack language easier, but it makes working with actual PHP more difficult.

**Comment by far-blue** [comment]
Thanks for everyone's work on this - most appreciated :)
